# Generated by Django 4.2.4 on 2023-09-14 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ecommerce_app', '0002_alter_product_available_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish_id', models.CharField(blank=True, max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Wishlist',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Wish_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce_app.product')),
                ('wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishlist_app.wishlist')),
            ],
            options={
                'db_table': 'Wish_item',
            },
        ),
    ]
